import hashlib
import hmac
import json

import pytest
from django.urls import reverse
from django.utils import timezone

from ingestion.models import IntakeSource
from outreach.models import Enrollment
from pipeline.models import Activity, Contact

from .factories import (
    ContactFactory,
    MailboxFactory,
    SequenceFactory,
    SequenceStepFactory,
    UserFactory,
)

pytestmark = pytest.mark.django_db


def _source(**kwargs):
    kwargs.setdefault("name", "Landing page")
    kwargs.setdefault("slug", "landing")
    kwargs.setdefault("owner", UserFactory())
    return IntakeSource.objects.create(**kwargs)


def _sign(secret, body: bytes):
    return hmac.new(secret.encode(), body, hashlib.sha256).hexdigest()


def _post_webhook(client, source, payload, signature=None):
    body = json.dumps(payload).encode()
    sig = signature if signature is not None else _sign(source.secret, body)
    return client.post(
        reverse("webhook-intake", args=[source.token]),
        data=body,
        content_type="application/json",
        HTTP_X_BYTEDOCKER_SIGNATURE=sig,
    )


# ---------------------------------------------------------------- model


def test_token_and_secret_autogenerated():
    source = _source()
    assert source.token and source.secret
    assert source.contact_source("webhook") == "webhook:landing"


# ---------------------------------------------------------------- webhook


def test_webhook_good_signature_creates_contact_and_lead(client):
    source = _source()
    response = _post_webhook(
        client,
        source,
        {"email": "CTO@Acme.com", "first_name": "Ada", "company": "Acme", "domain": "acme.com"},
    )
    assert response.status_code == 201
    assert response.json()["created"] is True
    contact = Contact.objects.get(email="cto@acme.com")  # normalized
    assert contact.owner == source.owner
    assert contact.source == "webhook:landing"
    assert contact.first_name == "Ada"
    assert contact.company.domain == "acme.com"
    assert contact.open_lead is not None


def test_webhook_bad_signature_403(client):
    source = _source()
    response = _post_webhook(client, source, {"email": "x@y.com"}, signature="deadbeef")
    assert response.status_code == 403
    assert not Contact.objects.exists()


def test_webhook_existing_contact_fills_blanks_returns_200(client):
    source = _source()
    existing = ContactFactory(email="cto@acme.com", first_name="", title="")
    response = _post_webhook(client, source, {"email": "cto@acme.com", "first_name": "Ada"})
    assert response.status_code == 200
    assert response.json()["created"] is False
    existing.refresh_from_db()
    assert existing.first_name == "Ada"  # blank filled


def test_webhook_invalid_email_400(client):
    source = _source()
    response = _post_webhook(client, source, {"email": "not-an-email"})
    assert response.status_code == 400


def test_webhook_unknown_token_404(client):
    response = client.post(
        reverse("webhook-intake", args=["nope"]),
        data=b"{}",
        content_type="application/json",
        HTTP_X_BYTEDOCKER_SIGNATURE="x",
    )
    assert response.status_code == 404


def test_webhook_inactive_source_404(client):
    source = _source(is_active=False)
    assert _post_webhook(client, source, {"email": "x@y.com"}).status_code == 404


# ---------------------------------------------------------------- auto-enroll


def test_auto_enroll_on_capture(client):
    mailbox = MailboxFactory()
    sequence = SequenceFactory()
    SequenceStepFactory(sequence=sequence, order=1)
    source = _source(auto_enroll=sequence, mailbox=mailbox)

    _post_webhook(client, source, {"email": "cto@acme.com"})

    contact = Contact.objects.get(email="cto@acme.com")
    enrollment = Enrollment.objects.get(contact=contact, sequence=sequence)
    assert enrollment.status == Enrollment.Status.ACTIVE
    assert enrollment.mailbox == mailbox
    assert enrollment.next_send_at is not None
    assert Activity.objects.filter(contact=contact, type=Activity.Type.ENROLLED).exists()


def test_no_auto_enroll_without_mailbox(client):
    source = _source(auto_enroll=SequenceFactory())  # no mailbox
    _post_webhook(client, source, {"email": "cto@acme.com"})
    assert not Enrollment.objects.exists()


def test_unsubscribed_contact_not_auto_enrolled(client):
    mailbox = MailboxFactory()
    sequence = SequenceFactory()
    source = _source(auto_enroll=sequence, mailbox=mailbox)
    ContactFactory(email="cto@acme.com", unsubscribed_at=timezone.now())

    _post_webhook(client, source, {"email": "cto@acme.com"})

    assert not Enrollment.objects.exists()


# ---------------------------------------------------------------- hosted form


def test_form_get_renders(client):
    source = _source()
    response = client.get(reverse("capture-form", args=[source.slug]))
    assert response.status_code == 200
    assert source.name.encode() in response.content


def test_form_post_creates_contact_with_source(client):
    source = _source()
    response = client.post(
        reverse("capture-form", args=[source.slug]),
        {"email": "lead@acme.com", "first_name": "Grace", "company": "Acme"},
    )
    assert response.status_code == 200
    assert b"we'll be in touch" in response.content
    contact = Contact.objects.get(email="lead@acme.com")
    assert contact.source == "form:landing"
    assert contact.open_lead is not None


def test_form_unknown_slug_404(client):
    assert client.get(reverse("capture-form", args=["ghost"])).status_code == 404


# ---------------------------------------------------------------- settings (admin)


def test_integrations_requires_admin(client):
    client.force_login(UserFactory(email="rep@x.com", role="rep"))
    assert client.get(reverse("integrations")).status_code == 403


def test_admin_creates_intake_source(client):
    client.force_login(UserFactory(email="admin@x.com", role="admin"))
    response = client.post(
        reverse("integration-create"), {"name": "Webinar", "slug": "webinar", "is_active": "on"}
    )
    assert response.status_code == 204
    source = IntakeSource.objects.get(slug="webinar")
    assert source.token and source.secret


def test_auto_enroll_requires_mailbox_in_form(client):
    client.force_login(UserFactory(email="admin@x.com", role="admin"))
    sequence = SequenceFactory()
    response = client.post(
        reverse("integration-create"),
        {"name": "X", "slug": "x", "auto_enroll": sequence.pk, "is_active": "on"},
    )
    assert response.status_code == 200  # re-rendered form with error
    assert b"sending mailbox" in response.content
