# Generated by Django 5.2.15 on 2026-06-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailbox",
            name="counters_reset_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
