# Generated by Django 5.2.15 on 2026-06-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0002_mailbox_counters_reset_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailbox",
            name="warmup",
            field=models.BooleanField(default=True),
        ),
    ]
