# Generated by Django 5.2.15 on 2026-06-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="enrichment_api_key",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
